# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="robbyrussell"
# ZSH_THEME="random"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="false"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=0

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

HISTSIZE=10000
# the number of saved commands in file after quit
SAVEHIST=100000
# The name of file in which commands history is saved
# HISTFILE=~/.zsh_history
# ignore duplicated command
setopt HIST_IGNORE_DUPS
# ignore command which starts with a space
setopt HIST_IGNORE_SPACE

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/etlugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
    git
    extract
    history-substring-search
    zsh-syntax-highlighting
    zsh-autosuggestions
)

# User configuration

export PATH=$HOME/bin:/usr/local/bin:$PATH
# export MANPATH="/usr/local/man:$MANPATH"

ZSH_DISABLE_COMPFIX=true

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# #AndroidStudio
# alias anstudio="/opt/android-studio/bin/studio.sh"

# # Intellij IDEA for java
# alias idea="/opt/idea-IC-139.225.3/bin/idea.sh"


#adb shell kill
alias mkill=". ~/linux_config/shell_tools/adb_shell_kill.sh"

#adb shell screen capture
alias mcapture=". ~/linux_config/shell_tools/adb_screencap.sh"

# rm recovert
# alias rm='. ~/linux_config/shell_tools/myrm.sh'

# auto color    
alias grep="grep --color"
# alias ls="ls -hF --color=tty"

# tags
alias mtags=". ~/linux_config/shell_tools/tags.sh"


# split file
alias msplit='sh ~/linux_config/shell_tools/split.sh'

# gh-md-toc
alias gh-md-toc='~/linux_config/bin_tools/gh-md-toc'

# A tiny utility to highlight multiple keywords with different colors
. ~/linux_config/shell_tools/h.sh

export SVN_EDITOR=vim

# replace autojump with z.lua
eval "$(lua /Applications/z.lua/z.lua --init zsh)"


# bind P and N for EMACS mode
bindkey '^p' history-substring-search-up
bindkey '^n' history-substring-search-down

bindkey '^j' autosuggest-accept

OS=`uname -s`
if [ ${OS} = "Darwin" ]; then
    # Mac OS X 操作系统
    # MacVimHome=/Applications/MacVim.app/Contents/MacOS
    # PATH=/Users/00390839/Library/hugo_0.56.0_macOS-64bit:$PATH
    # alias vi="/Applications/MacVim.app/Contents/MacOS/Vim -u ~/.vim/vimrc.simple" 
    # alias vim="/Applications/MacVim.app/Contents/MacOS/Vim -u ~/.vim/vimrc" 
    # alias vi=${MacVimHome}"/Vim -u ~/.vim/vimrc.simple"
    # alias vim=${MacVimHome}"/Vim -u ~/.vim/vimrc"
    alias vscode="/Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron"


	# java 
	JAVA_HOME=/Applications/Android\ Studio.app/Contents/jre/jdk/Contents/Home
	JRE_HOME=$JAVA_HOME/lib
	PATH=$JAVA_HOME/bin:$JRE_HOME/bin:$PATH

	# anroid Sdk
	ANDROID_SDK=~/Library/Android/sdk
	PATH=$ANDROID_SDK/build-tools:$ANDROID_SDK/platform-tools:$ANDROID_SDK/tools:$PATH
elif [ ${OS} = "Linux"  ]; then
    alias vi="vim -u ~/.vim/vimrc.simple"
elif [ ${OS} = "MINGW32_NT" ]; then
    # wsl
    alias gvim="/mnt/c/gvim_8.0.0003_x64/vim/vim80/gvim.exe %1"
    alias wuser="/mnt/c/users/muqing/"
    echo "Other OS: ${OS}"
fi

export PATH=$PATH
